/* Generated by tools/make_init.R -- do not edit by hand. */

#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>
#include <R_ext/Visibility.h>

extern "C" SEXP coinclp_add_columns(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_add_rows(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_algorithm(SEXP);
extern "C" SEXP coinclp_check_solution(SEXP);
extern "C" SEXP coinclp_chg_column_lower(SEXP, SEXP);
extern "C" SEXP coinclp_chg_column_upper(SEXP, SEXP);
extern "C" SEXP coinclp_chg_objective(SEXP, SEXP);
extern "C" SEXP coinclp_chg_row_lower(SEXP, SEXP);
extern "C" SEXP coinclp_chg_row_upper(SEXP, SEXP);
extern "C" SEXP coinclp_column_lower(SEXP);
extern "C" SEXP coinclp_column_name(SEXP, SEXP);
extern "C" SEXP coinclp_column_upper(SEXP);
extern "C" SEXP coinclp_copy_in_integer_information(SEXP, SEXP);
extern "C" SEXP coinclp_copy_names(SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_copyin_status(SEXP, SEXP);
extern "C" SEXP coinclp_crash(SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_delete_columns(SEXP, SEXP);
extern "C" SEXP coinclp_delete_integer_information(SEXP);
extern "C" SEXP coinclp_delete_model(SEXP);
extern "C" SEXP coinclp_delete_options(SEXP);
extern "C" SEXP coinclp_delete_rows(SEXP, SEXP);
extern "C" SEXP coinclp_drop_names(SEXP);
extern "C" SEXP coinclp_dual(SEXP, SEXP);
extern "C" SEXP coinclp_dual_bound(SEXP);
extern "C" SEXP coinclp_dual_column_solution(SEXP);
extern "C" SEXP coinclp_dual_feasible(SEXP);
extern "C" SEXP coinclp_dual_objective_limit(SEXP);
extern "C" SEXP coinclp_dual_row_solution(SEXP);
extern "C" SEXP coinclp_dual_tolerance(SEXP);
extern "C" SEXP coinclp_elements(SEXP);
extern "C" SEXP coinclp_features(void);
extern "C" SEXP coinclp_get_column_status(SEXP, SEXP);
extern "C" SEXP coinclp_get_row_status(SEXP, SEXP);
extern "C" SEXP coinclp_hit_maximum_iterations(SEXP);
extern "C" SEXP coinclp_idiot(SEXP, SEXP);
extern "C" SEXP coinclp_indices(SEXP);
extern "C" SEXP coinclp_infeasibility_cost(SEXP);
extern "C" SEXP coinclp_infeasibility_ray(SEXP);
extern "C" SEXP coinclp_initial_barrier_no_cross_solve(SEXP);
extern "C" SEXP coinclp_initial_barrier_solve(SEXP);
extern "C" SEXP coinclp_initial_dual_solve(SEXP);
extern "C" SEXP coinclp_initial_primal_solve(SEXP);
extern "C" SEXP coinclp_initial_solve(SEXP);
extern "C" SEXP coinclp_initial_solve_with_options(SEXP, SEXP);
extern "C" SEXP coinclp_integer_information(SEXP);
extern "C" SEXP coinclp_is_abandoned(SEXP);
extern "C" SEXP coinclp_is_dual_objective_limit_reached(SEXP);
extern "C" SEXP coinclp_is_iteration_limit_reached(SEXP);
extern "C" SEXP coinclp_is_primal_objective_limit_reached(SEXP);
extern "C" SEXP coinclp_is_proven_dual_infeasible(SEXP);
extern "C" SEXP coinclp_is_proven_optimal(SEXP);
extern "C" SEXP coinclp_is_proven_primal_infeasible(SEXP);
extern "C" SEXP coinclp_length_names(SEXP);
extern "C" SEXP coinclp_load_problem(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_load_quadratic(SEXP, SEXP, SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_log_level(SEXP);
extern "C" SEXP coinclp_matrix_triplets(SEXP);
extern "C" SEXP coinclp_maximum_iterations(SEXP);
extern "C" SEXP coinclp_maximum_seconds(SEXP);
extern "C" SEXP coinclp_model_is_open(SEXP);
extern "C" SEXP coinclp_modify_coefficient(SEXP, SEXP, SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_new_model(void);
extern "C" SEXP coinclp_new_options(void);
extern "C" SEXP coinclp_number_columns(SEXP);
extern "C" SEXP coinclp_number_dual_infeasibilities(SEXP);
extern "C" SEXP coinclp_number_elements(SEXP);
extern "C" SEXP coinclp_number_iterations(SEXP);
extern "C" SEXP coinclp_number_primal_infeasibilities(SEXP);
extern "C" SEXP coinclp_number_rows(SEXP);
extern "C" SEXP coinclp_obj_sense(SEXP);
extern "C" SEXP coinclp_objective(SEXP);
extern "C" SEXP coinclp_objective_offset(SEXP);
extern "C" SEXP coinclp_objective_value(SEXP);
extern "C" SEXP coinclp_optimization_direction(SEXP);
extern "C" SEXP coinclp_options_do_doubleton(SEXP);
extern "C" SEXP coinclp_options_do_dual(SEXP);
extern "C" SEXP coinclp_options_do_dupcol(SEXP);
extern "C" SEXP coinclp_options_do_duprow(SEXP);
extern "C" SEXP coinclp_options_do_forcing(SEXP);
extern "C" SEXP coinclp_options_do_implied_free(SEXP);
extern "C" SEXP coinclp_options_do_singleton(SEXP);
extern "C" SEXP coinclp_options_do_singleton_column(SEXP);
extern "C" SEXP coinclp_options_do_tighten(SEXP);
extern "C" SEXP coinclp_options_do_tripleton(SEXP);
extern "C" SEXP coinclp_options_get_extra_info(SEXP, SEXP);
extern "C" SEXP coinclp_options_get_presolve_passes(SEXP);
extern "C" SEXP coinclp_options_get_presolve_type(SEXP);
extern "C" SEXP coinclp_options_get_solve_type(SEXP);
extern "C" SEXP coinclp_options_get_special_option(SEXP, SEXP);
extern "C" SEXP coinclp_options_infeasible_return(SEXP);
extern "C" SEXP coinclp_options_presolve_actions(SEXP);
extern "C" SEXP coinclp_options_set_do_doubleton(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_do_dual(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_do_dupcol(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_do_duprow(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_do_forcing(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_do_implied_free(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_do_singleton(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_do_singleton_column(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_do_tighten(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_do_tripleton(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_infeasible_return(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_presolve_actions(SEXP, SEXP);
extern "C" SEXP coinclp_options_set_presolve_type(SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_options_set_solve_type(SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_options_set_special_option(SEXP, SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_options_set_substitution(SEXP, SEXP);
extern "C" SEXP coinclp_options_substitution(SEXP);
extern "C" SEXP coinclp_perturbation(SEXP);
extern "C" SEXP coinclp_primal(SEXP, SEXP);
extern "C" SEXP coinclp_primal_column_solution(SEXP);
extern "C" SEXP coinclp_primal_feasible(SEXP);
extern "C" SEXP coinclp_primal_row_solution(SEXP);
extern "C" SEXP coinclp_primal_tolerance(SEXP);
extern "C" SEXP coinclp_print_model(SEXP, SEXP);
extern "C" SEXP coinclp_problem_name(SEXP);
extern "C" SEXP coinclp_read_mps(SEXP, SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_resize(SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_restore_model(SEXP, SEXP);
extern "C" SEXP coinclp_row_lower(SEXP);
extern "C" SEXP coinclp_row_name(SEXP, SEXP);
extern "C" SEXP coinclp_row_upper(SEXP);
extern "C" SEXP coinclp_save_model(SEXP, SEXP);
extern "C" SEXP coinclp_scaling_flag(SEXP);
extern "C" SEXP coinclp_secondary_status(SEXP);
extern "C" SEXP coinclp_set_algorithm(SEXP, SEXP);
extern "C" SEXP coinclp_set_column_name(SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_set_column_solution(SEXP, SEXP);
extern "C" SEXP coinclp_set_column_status(SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_set_dual_bound(SEXP, SEXP);
extern "C" SEXP coinclp_set_dual_objective_limit(SEXP, SEXP);
extern "C" SEXP coinclp_set_dual_tolerance(SEXP, SEXP);
extern "C" SEXP coinclp_set_infeasibility_cost(SEXP, SEXP);
extern "C" SEXP coinclp_set_log_level(SEXP, SEXP);
extern "C" SEXP coinclp_set_maximum_iterations(SEXP, SEXP);
extern "C" SEXP coinclp_set_maximum_seconds(SEXP, SEXP);
extern "C" SEXP coinclp_set_number_iterations(SEXP, SEXP);
extern "C" SEXP coinclp_set_obj_sense(SEXP, SEXP);
extern "C" SEXP coinclp_set_objective_offset(SEXP, SEXP);
extern "C" SEXP coinclp_set_optimization_direction(SEXP, SEXP);
extern "C" SEXP coinclp_set_perturbation(SEXP, SEXP);
extern "C" SEXP coinclp_set_primal_tolerance(SEXP, SEXP);
extern "C" SEXP coinclp_set_problem_name(SEXP, SEXP);
extern "C" SEXP coinclp_set_problem_status(SEXP, SEXP);
extern "C" SEXP coinclp_set_row_name(SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_set_row_status(SEXP, SEXP, SEXP);
extern "C" SEXP coinclp_set_scaling(SEXP, SEXP);
extern "C" SEXP coinclp_set_secondary_status(SEXP, SEXP);
extern "C" SEXP coinclp_set_small_element_value(SEXP, SEXP);
extern "C" SEXP coinclp_small_element_value(SEXP);
extern "C" SEXP coinclp_status(SEXP);
extern "C" SEXP coinclp_status_array(SEXP);
extern "C" SEXP coinclp_status_exists(SEXP);
extern "C" SEXP coinclp_sum_dual_infeasibilities(SEXP);
extern "C" SEXP coinclp_sum_primal_infeasibilities(SEXP);
extern "C" SEXP coinclp_unbounded_ray(SEXP);
extern "C" SEXP coinclp_vector_lengths(SEXP);
extern "C" SEXP coinclp_vector_starts(SEXP);
extern "C" SEXP coinclp_version(void);
extern "C" SEXP coinclp_write_mps(SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef call_methods[] = {
    {"coinclp_add_columns", (DL_FUNC) &coinclp_add_columns, 8},
    {"coinclp_add_rows", (DL_FUNC) &coinclp_add_rows, 7},
    {"coinclp_algorithm", (DL_FUNC) &coinclp_algorithm, 1},
    {"coinclp_check_solution", (DL_FUNC) &coinclp_check_solution, 1},
    {"coinclp_chg_column_lower", (DL_FUNC) &coinclp_chg_column_lower, 2},
    {"coinclp_chg_column_upper", (DL_FUNC) &coinclp_chg_column_upper, 2},
    {"coinclp_chg_objective", (DL_FUNC) &coinclp_chg_objective, 2},
    {"coinclp_chg_row_lower", (DL_FUNC) &coinclp_chg_row_lower, 2},
    {"coinclp_chg_row_upper", (DL_FUNC) &coinclp_chg_row_upper, 2},
    {"coinclp_column_lower", (DL_FUNC) &coinclp_column_lower, 1},
    {"coinclp_column_name", (DL_FUNC) &coinclp_column_name, 2},
    {"coinclp_column_upper", (DL_FUNC) &coinclp_column_upper, 1},
    {"coinclp_copy_in_integer_information", (DL_FUNC) &coinclp_copy_in_integer_information, 2},
    {"coinclp_copy_names", (DL_FUNC) &coinclp_copy_names, 3},
    {"coinclp_copyin_status", (DL_FUNC) &coinclp_copyin_status, 2},
    {"coinclp_crash", (DL_FUNC) &coinclp_crash, 3},
    {"coinclp_delete_columns", (DL_FUNC) &coinclp_delete_columns, 2},
    {"coinclp_delete_integer_information", (DL_FUNC) &coinclp_delete_integer_information, 1},
    {"coinclp_delete_model", (DL_FUNC) &coinclp_delete_model, 1},
    {"coinclp_delete_options", (DL_FUNC) &coinclp_delete_options, 1},
    {"coinclp_delete_rows", (DL_FUNC) &coinclp_delete_rows, 2},
    {"coinclp_drop_names", (DL_FUNC) &coinclp_drop_names, 1},
    {"coinclp_dual", (DL_FUNC) &coinclp_dual, 2},
    {"coinclp_dual_bound", (DL_FUNC) &coinclp_dual_bound, 1},
    {"coinclp_dual_column_solution", (DL_FUNC) &coinclp_dual_column_solution, 1},
    {"coinclp_dual_feasible", (DL_FUNC) &coinclp_dual_feasible, 1},
    {"coinclp_dual_objective_limit", (DL_FUNC) &coinclp_dual_objective_limit, 1},
    {"coinclp_dual_row_solution", (DL_FUNC) &coinclp_dual_row_solution, 1},
    {"coinclp_dual_tolerance", (DL_FUNC) &coinclp_dual_tolerance, 1},
    {"coinclp_elements", (DL_FUNC) &coinclp_elements, 1},
    {"coinclp_features", (DL_FUNC) &coinclp_features, 0},
    {"coinclp_get_column_status", (DL_FUNC) &coinclp_get_column_status, 2},
    {"coinclp_get_row_status", (DL_FUNC) &coinclp_get_row_status, 2},
    {"coinclp_hit_maximum_iterations", (DL_FUNC) &coinclp_hit_maximum_iterations, 1},
    {"coinclp_idiot", (DL_FUNC) &coinclp_idiot, 2},
    {"coinclp_indices", (DL_FUNC) &coinclp_indices, 1},
    {"coinclp_infeasibility_cost", (DL_FUNC) &coinclp_infeasibility_cost, 1},
    {"coinclp_infeasibility_ray", (DL_FUNC) &coinclp_infeasibility_ray, 1},
    {"coinclp_initial_barrier_no_cross_solve", (DL_FUNC) &coinclp_initial_barrier_no_cross_solve, 1},
    {"coinclp_initial_barrier_solve", (DL_FUNC) &coinclp_initial_barrier_solve, 1},
    {"coinclp_initial_dual_solve", (DL_FUNC) &coinclp_initial_dual_solve, 1},
    {"coinclp_initial_primal_solve", (DL_FUNC) &coinclp_initial_primal_solve, 1},
    {"coinclp_initial_solve", (DL_FUNC) &coinclp_initial_solve, 1},
    {"coinclp_initial_solve_with_options", (DL_FUNC) &coinclp_initial_solve_with_options, 2},
    {"coinclp_integer_information", (DL_FUNC) &coinclp_integer_information, 1},
    {"coinclp_is_abandoned", (DL_FUNC) &coinclp_is_abandoned, 1},
    {"coinclp_is_dual_objective_limit_reached", (DL_FUNC) &coinclp_is_dual_objective_limit_reached, 1},
    {"coinclp_is_iteration_limit_reached", (DL_FUNC) &coinclp_is_iteration_limit_reached, 1},
    {"coinclp_is_primal_objective_limit_reached", (DL_FUNC) &coinclp_is_primal_objective_limit_reached, 1},
    {"coinclp_is_proven_dual_infeasible", (DL_FUNC) &coinclp_is_proven_dual_infeasible, 1},
    {"coinclp_is_proven_optimal", (DL_FUNC) &coinclp_is_proven_optimal, 1},
    {"coinclp_is_proven_primal_infeasible", (DL_FUNC) &coinclp_is_proven_primal_infeasible, 1},
    {"coinclp_length_names", (DL_FUNC) &coinclp_length_names, 1},
    {"coinclp_load_problem", (DL_FUNC) &coinclp_load_problem, 11},
    {"coinclp_load_quadratic", (DL_FUNC) &coinclp_load_quadratic, 5},
    {"coinclp_log_level", (DL_FUNC) &coinclp_log_level, 1},
    {"coinclp_matrix_triplets", (DL_FUNC) &coinclp_matrix_triplets, 1},
    {"coinclp_maximum_iterations", (DL_FUNC) &coinclp_maximum_iterations, 1},
    {"coinclp_maximum_seconds", (DL_FUNC) &coinclp_maximum_seconds, 1},
    {"coinclp_model_is_open", (DL_FUNC) &coinclp_model_is_open, 1},
    {"coinclp_modify_coefficient", (DL_FUNC) &coinclp_modify_coefficient, 5},
    {"coinclp_new_model", (DL_FUNC) &coinclp_new_model, 0},
    {"coinclp_new_options", (DL_FUNC) &coinclp_new_options, 0},
    {"coinclp_number_columns", (DL_FUNC) &coinclp_number_columns, 1},
    {"coinclp_number_dual_infeasibilities", (DL_FUNC) &coinclp_number_dual_infeasibilities, 1},
    {"coinclp_number_elements", (DL_FUNC) &coinclp_number_elements, 1},
    {"coinclp_number_iterations", (DL_FUNC) &coinclp_number_iterations, 1},
    {"coinclp_number_primal_infeasibilities", (DL_FUNC) &coinclp_number_primal_infeasibilities, 1},
    {"coinclp_number_rows", (DL_FUNC) &coinclp_number_rows, 1},
    {"coinclp_obj_sense", (DL_FUNC) &coinclp_obj_sense, 1},
    {"coinclp_objective", (DL_FUNC) &coinclp_objective, 1},
    {"coinclp_objective_offset", (DL_FUNC) &coinclp_objective_offset, 1},
    {"coinclp_objective_value", (DL_FUNC) &coinclp_objective_value, 1},
    {"coinclp_optimization_direction", (DL_FUNC) &coinclp_optimization_direction, 1},
    {"coinclp_options_do_doubleton", (DL_FUNC) &coinclp_options_do_doubleton, 1},
    {"coinclp_options_do_dual", (DL_FUNC) &coinclp_options_do_dual, 1},
    {"coinclp_options_do_dupcol", (DL_FUNC) &coinclp_options_do_dupcol, 1},
    {"coinclp_options_do_duprow", (DL_FUNC) &coinclp_options_do_duprow, 1},
    {"coinclp_options_do_forcing", (DL_FUNC) &coinclp_options_do_forcing, 1},
    {"coinclp_options_do_implied_free", (DL_FUNC) &coinclp_options_do_implied_free, 1},
    {"coinclp_options_do_singleton", (DL_FUNC) &coinclp_options_do_singleton, 1},
    {"coinclp_options_do_singleton_column", (DL_FUNC) &coinclp_options_do_singleton_column, 1},
    {"coinclp_options_do_tighten", (DL_FUNC) &coinclp_options_do_tighten, 1},
    {"coinclp_options_do_tripleton", (DL_FUNC) &coinclp_options_do_tripleton, 1},
    {"coinclp_options_get_extra_info", (DL_FUNC) &coinclp_options_get_extra_info, 2},
    {"coinclp_options_get_presolve_passes", (DL_FUNC) &coinclp_options_get_presolve_passes, 1},
    {"coinclp_options_get_presolve_type", (DL_FUNC) &coinclp_options_get_presolve_type, 1},
    {"coinclp_options_get_solve_type", (DL_FUNC) &coinclp_options_get_solve_type, 1},
    {"coinclp_options_get_special_option", (DL_FUNC) &coinclp_options_get_special_option, 2},
    {"coinclp_options_infeasible_return", (DL_FUNC) &coinclp_options_infeasible_return, 1},
    {"coinclp_options_presolve_actions", (DL_FUNC) &coinclp_options_presolve_actions, 1},
    {"coinclp_options_set_do_doubleton", (DL_FUNC) &coinclp_options_set_do_doubleton, 2},
    {"coinclp_options_set_do_dual", (DL_FUNC) &coinclp_options_set_do_dual, 2},
    {"coinclp_options_set_do_dupcol", (DL_FUNC) &coinclp_options_set_do_dupcol, 2},
    {"coinclp_options_set_do_duprow", (DL_FUNC) &coinclp_options_set_do_duprow, 2},
    {"coinclp_options_set_do_forcing", (DL_FUNC) &coinclp_options_set_do_forcing, 2},
    {"coinclp_options_set_do_implied_free", (DL_FUNC) &coinclp_options_set_do_implied_free, 2},
    {"coinclp_options_set_do_singleton", (DL_FUNC) &coinclp_options_set_do_singleton, 2},
    {"coinclp_options_set_do_singleton_column", (DL_FUNC) &coinclp_options_set_do_singleton_column, 2},
    {"coinclp_options_set_do_tighten", (DL_FUNC) &coinclp_options_set_do_tighten, 2},
    {"coinclp_options_set_do_tripleton", (DL_FUNC) &coinclp_options_set_do_tripleton, 2},
    {"coinclp_options_set_infeasible_return", (DL_FUNC) &coinclp_options_set_infeasible_return, 2},
    {"coinclp_options_set_presolve_actions", (DL_FUNC) &coinclp_options_set_presolve_actions, 2},
    {"coinclp_options_set_presolve_type", (DL_FUNC) &coinclp_options_set_presolve_type, 3},
    {"coinclp_options_set_solve_type", (DL_FUNC) &coinclp_options_set_solve_type, 3},
    {"coinclp_options_set_special_option", (DL_FUNC) &coinclp_options_set_special_option, 4},
    {"coinclp_options_set_substitution", (DL_FUNC) &coinclp_options_set_substitution, 2},
    {"coinclp_options_substitution", (DL_FUNC) &coinclp_options_substitution, 1},
    {"coinclp_perturbation", (DL_FUNC) &coinclp_perturbation, 1},
    {"coinclp_primal", (DL_FUNC) &coinclp_primal, 2},
    {"coinclp_primal_column_solution", (DL_FUNC) &coinclp_primal_column_solution, 1},
    {"coinclp_primal_feasible", (DL_FUNC) &coinclp_primal_feasible, 1},
    {"coinclp_primal_row_solution", (DL_FUNC) &coinclp_primal_row_solution, 1},
    {"coinclp_primal_tolerance", (DL_FUNC) &coinclp_primal_tolerance, 1},
    {"coinclp_print_model", (DL_FUNC) &coinclp_print_model, 2},
    {"coinclp_problem_name", (DL_FUNC) &coinclp_problem_name, 1},
    {"coinclp_read_mps", (DL_FUNC) &coinclp_read_mps, 4},
    {"coinclp_resize", (DL_FUNC) &coinclp_resize, 3},
    {"coinclp_restore_model", (DL_FUNC) &coinclp_restore_model, 2},
    {"coinclp_row_lower", (DL_FUNC) &coinclp_row_lower, 1},
    {"coinclp_row_name", (DL_FUNC) &coinclp_row_name, 2},
    {"coinclp_row_upper", (DL_FUNC) &coinclp_row_upper, 1},
    {"coinclp_save_model", (DL_FUNC) &coinclp_save_model, 2},
    {"coinclp_scaling_flag", (DL_FUNC) &coinclp_scaling_flag, 1},
    {"coinclp_secondary_status", (DL_FUNC) &coinclp_secondary_status, 1},
    {"coinclp_set_algorithm", (DL_FUNC) &coinclp_set_algorithm, 2},
    {"coinclp_set_column_name", (DL_FUNC) &coinclp_set_column_name, 3},
    {"coinclp_set_column_solution", (DL_FUNC) &coinclp_set_column_solution, 2},
    {"coinclp_set_column_status", (DL_FUNC) &coinclp_set_column_status, 3},
    {"coinclp_set_dual_bound", (DL_FUNC) &coinclp_set_dual_bound, 2},
    {"coinclp_set_dual_objective_limit", (DL_FUNC) &coinclp_set_dual_objective_limit, 2},
    {"coinclp_set_dual_tolerance", (DL_FUNC) &coinclp_set_dual_tolerance, 2},
    {"coinclp_set_infeasibility_cost", (DL_FUNC) &coinclp_set_infeasibility_cost, 2},
    {"coinclp_set_log_level", (DL_FUNC) &coinclp_set_log_level, 2},
    {"coinclp_set_maximum_iterations", (DL_FUNC) &coinclp_set_maximum_iterations, 2},
    {"coinclp_set_maximum_seconds", (DL_FUNC) &coinclp_set_maximum_seconds, 2},
    {"coinclp_set_number_iterations", (DL_FUNC) &coinclp_set_number_iterations, 2},
    {"coinclp_set_obj_sense", (DL_FUNC) &coinclp_set_obj_sense, 2},
    {"coinclp_set_objective_offset", (DL_FUNC) &coinclp_set_objective_offset, 2},
    {"coinclp_set_optimization_direction", (DL_FUNC) &coinclp_set_optimization_direction, 2},
    {"coinclp_set_perturbation", (DL_FUNC) &coinclp_set_perturbation, 2},
    {"coinclp_set_primal_tolerance", (DL_FUNC) &coinclp_set_primal_tolerance, 2},
    {"coinclp_set_problem_name", (DL_FUNC) &coinclp_set_problem_name, 2},
    {"coinclp_set_problem_status", (DL_FUNC) &coinclp_set_problem_status, 2},
    {"coinclp_set_row_name", (DL_FUNC) &coinclp_set_row_name, 3},
    {"coinclp_set_row_status", (DL_FUNC) &coinclp_set_row_status, 3},
    {"coinclp_set_scaling", (DL_FUNC) &coinclp_set_scaling, 2},
    {"coinclp_set_secondary_status", (DL_FUNC) &coinclp_set_secondary_status, 2},
    {"coinclp_set_small_element_value", (DL_FUNC) &coinclp_set_small_element_value, 2},
    {"coinclp_small_element_value", (DL_FUNC) &coinclp_small_element_value, 1},
    {"coinclp_status", (DL_FUNC) &coinclp_status, 1},
    {"coinclp_status_array", (DL_FUNC) &coinclp_status_array, 1},
    {"coinclp_status_exists", (DL_FUNC) &coinclp_status_exists, 1},
    {"coinclp_sum_dual_infeasibilities", (DL_FUNC) &coinclp_sum_dual_infeasibilities, 1},
    {"coinclp_sum_primal_infeasibilities", (DL_FUNC) &coinclp_sum_primal_infeasibilities, 1},
    {"coinclp_unbounded_ray", (DL_FUNC) &coinclp_unbounded_ray, 1},
    {"coinclp_vector_lengths", (DL_FUNC) &coinclp_vector_lengths, 1},
    {"coinclp_vector_starts", (DL_FUNC) &coinclp_vector_starts, 1},
    {"coinclp_version", (DL_FUNC) &coinclp_version, 0},
    {"coinclp_write_mps", (DL_FUNC) &coinclp_write_mps, 5},
    {NULL, NULL, 0}
};

extern "C" attribute_visible void R_init_coinclp(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, call_methods, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    R_forceSymbols(dll, TRUE);
}
